/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kasirapp.views;

import javax.swing.*;
import java.awt.*;

/**
 * @author Refi
 */
public class AdminPage extends javax.swing.JPanel {

    public AdminPage(MainFrame frame) {
        setLayout(new GridBagLayout());
        setBackground(new Color(0, 40, 85)); // Warna sama seperti KasirPage dan LoginPage

        // Panel utama (isi dashboard)
        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setPreferredSize(new Dimension(500, 400));
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220), 1, true));

        GridBagConstraints p = new GridBagConstraints();
        p.insets = new Insets(15, 10, 15, 10);
        p.fill = GridBagConstraints.HORIZONTAL;
        p.gridx = 0;
        p.gridwidth = 2;

        // Judul
        JLabel lblTitle = new JLabel("Dashboard Admin", SwingConstants.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblTitle.setForeground(new Color(33, 37, 41));
        p.gridy = 0;
        panel.add(lblTitle, p);

        // Tombol Kelola Barang
        JButton btnBarang = new JButton("Kelola Barang");
        styleButton(btnBarang, new Color(0, 40, 85));
        p.gridy = 1;
        panel.add(btnBarang, p);

        // Tombol Kelola Akun Kasir
        JButton btnAkun = new JButton("Kelola Akun Kasir");
        styleButton(btnAkun, new Color(0, 40, 85));
        p.gridy = 2;
        panel.add(btnAkun, p);

        // Tombol Laporan Penjualan
        JButton btnLaporan = new JButton("Laporan Penjualan");
        styleButton(btnLaporan, new Color(0, 40, 85));
        p.gridy = 3;
        panel.add(btnLaporan, p);

        // Tombol Logout
        JButton btnLogout = new JButton("Logout");
        styleButton(btnLogout, new Color(220, 53, 69));
        p.gridy = 4;
        panel.add(btnLogout, p);

        // Tambahkan panel utama ke tengah layar
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        add(panel, gbc);

        // Aksi tombol
        btnBarang.addActionListener(e -> frame.showPage("KelolaBarang"));
        btnAkun.addActionListener(e -> frame.showPage("KelolaAkun"));
        btnLaporan.addActionListener(e -> frame.showPage("Laporan"));
        btnLogout.addActionListener(e -> frame.showPage("Login"));
    }

    private void styleButton(JButton button, Color color) {
        button.setBackground(color);
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setFont(new Font("Segoe UI", Font.BOLD, 14));
        button.setPreferredSize(new Dimension(200, 40));
        button.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
