
package kasirapp.views;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * @author Refi
 */
public final class MainFrame extends javax.swing.JFrame {

      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final CardLayout cardLayout;
    private final JPanel mainPanel;

    public MainFrame() {
        
        setTitle("Sistem Kasir Sederhana");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 500);
        setLocationRelativeTo(null);

        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        // Tambahkan halaman
        mainPanel.add(new LoginPage(this), "Login");
        mainPanel.add(new AdminPage(this), "Admin");
        mainPanel.add(new KasirPage(this), "Kasir");
        mainPanel.add(new KelolaBarangPage(this), "KelolaBarang");
        mainPanel.add(new KelolaAkunPage(this), "KelolaAkun");
        mainPanel.add(new LaporanPage(this), "Laporan");



        add(mainPanel);
        showPage("Login");
        
        setVisible(true);
    }

    public void showPage(String name) {
        cardLayout.show(mainPanel, name);
    }
        public static void main(String[] args) {
        SwingUtilities.invokeLater(MainFrame::new);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setAdmin(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}